version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/stayeasy
      - JWT_SECRET=your_jwt_secret
      - TWILIO_SID=your_twilio_sid
      - TWILIO_TOKEN=your_twilio_token
      - TWILIO_PHONE=your_twilio_phone

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stayeasy
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: